#!/usr/bin/env bash
# Regenerates the frontend ABI from the compiled Telebuzzy contract.
# CI runs this and fails if the committed file differs.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT_FILE="../telebuzzy-frontend/src/config/web3/abi.ts"

{
  echo "// Generated by telebuzzy-solidity/scripts/export-abi.sh — do not edit by hand."
  printf "export const telebuzzyContractAbi = "
  forge inspect Telebuzzy abi --json | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>process.stdout.write(JSON.stringify(JSON.parse(s),null,2)))'
  echo " as const;"
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"
